### ISSUE TITLE
onEdit event problems with react hooks

### ISSUE THREAD

**Issue by xfishernet** [alex3165/react-leaflet-draw#65]
onCreated event work fine, but onEdit event call very strange, all state variables undefined (

**Comment by marzukia** [comment]
occurs onDeleted too - any help please?

**Comment by jmloewen** [comment]
I am also experiencing this.  Specifically the strange interaction I get is this:

I have a useState value called `features`, updated via `setFeatures`.  `setFeatures` is called within a callback function within my container, let's call it `LocationForm`.  This `LocationForm` holds a `MapContainer` which contains the React-Leaflet-Map, using React-Leaflet-Draw.

When I draw an item using the `EditControl`, my _onCreated function is called.  This function calls my callback in `LocationForm`, appending the feature data generated by `EditControl`.  This feature data is added to my `features` object in the callback.  I can do this as many times as I would like, and it works perfectly.

When I use the Edit functionality within `EditControl` and then click Save, my _onEdited function is called.  This function does the same thing as _onCreated, with the exception that the data is formatted differently.  It also sends its same data back upstream to my callback function, with the Key and the Values to be updated.

This is where I run into problems (_onDeleted has this same issue).

When I look at `features` from the perspective of the callback called via the _onCreated function, I am shown my entire list of `features` as created by _onCreated.

However, when I look at `features` from the perspective of the callback called via the _onEdited function, I am shown only the empty value initialized by useState, in this case, an empty object.

If I instead look at the EditControl functions, and assign onEdited={_onCreated}, I experience this same issue - if I try to look at this list of features from the perspective of anything except the onCreated parameter coming from EditControl, I get the initial value set in useState.

However, I am able to use the `setFeatures` function from the perspective of my other callback functions - if I hit my callback via onEdited, I can certainly use setFeatures to create a new list of features.  I cannot, however, the existing value of features, and I require this in order to retrieve the geoJSON of the updated feature on the map.

This also happens when using onDeleted, and also occurs when using data types like Arrays and Integers.

Callback function in the parent Form:
```javascript
const featuresCallback = layers => {
    console.log("features in callback before action is: ", features)
    console.log("layers in features callback is: ", layers)
    if (layers && layers.geometry && layers.geometry.type) { //new item

      const newFeature = { ...features };
      newFeature[layers.leaflet_id] = layers;

      setFeatures(newFeature);
    } 
}
```
OnCreated / OnEdited: 

```javascript
const _onCreated = e => {
    let type = e.layerType;
    let layer = e.layer;

    let newFeature = {
      leaflet_id: layer._leaflet_id, //may have to remove before submission to API
      type: 'Feature',
      geometry: {
        type: type == 'marker' ? 'Point' : type == 'polyline' ? 'LineString' : 'Polygon',
        coordinates: layer._latlng ? layer._latlng : layer._latlngs,
      },
    };
    
    //Update the list of created items.
    featuresCallback(newFeature);
  };

const _onEdited = e => {

    let editKey = Object.keys(e.layers._layers)[0]
    let editedItem = e.layers._layers[editKey]

    const editedFeature = {
        leaflet_id: editedItem._leaflet_id,
        type: "Feature",
        geometry: {
            coordinates: layers._latlng ? layers._latlng : layers._latlngs
        }
    }

    featuresCallback(editedFeature)
}
```
FeatureGroup declaration
```javascript

<FeatureGroup ref={ (fGroup) => {setFGroup(fGroup)}}>
            <EditControl
              position="topleft"
              onCreated={_onCreated}
              onEdited={_onEdited}
              /*onEdited={e => {
                  e.layers.eachLayer(a => {
                      console.log("a: ", a)
                      featuresCallback({id: a._leaflet_id,
                      feature: a.toGeoJSON()})
                  })
              }}*/
              onDeleted={_onDeleted}
              draw={{
                rectangle: false,
                circle: false,
                circlemarker: false,
              }}
            />
          </FeatureGroup>
```

Screenshot of the console log, showing that after `_onCreated`, features is populated, but that we cannot see this data when accessing the same callback via `_onEdited`

![image](https://user-images.githubusercontent.com/14321512/64573109-f2f2f880-d31e-11e9-8117-7d1d31162924.png)

**Comment by jmloewen** [comment]
I resolved this issue by converting my component into a class and just ditching Hooks for this component.  I did this after noticing that all Starred repo's using the EditControl's onEdited functionality store and manage their data on the same level as the EditControl.

After switching back to a class-based component, things work just fine - the issue must be some sort of quirky interaction with Hooks.
